name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and run tests
      run: |
        docker compose --profile test build
        docker compose --profile test run --rm test

    - name: Cleanup
      if: always()
      run: docker compose down --remove-orphans